# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-03 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestatus',
            name='status',
            field=models.BooleanField(choices=[(True, '赞'), (False, '踩')], verbose_name='赞踩状态'),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, ' OpenStack'), (4, ' GoLang')], default=None, verbose_name='文章种类'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(upload_to='static/user_img', verbose_name='头像'),
        ),
    ]
