# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-04 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20180803_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestatus',
            name='status',
            field=models.BooleanField(choices=[(False, '踩'), (True, '赞')], verbose_name='赞踩状态'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(null=True, upload_to='static/user_img', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=32, null=True, verbose_name='昵称'),
        ),
    ]
