# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20180804_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestatus',
            name='status',
            field=models.BooleanField(choices=[(True, '赞'), (False, '踩')], verbose_name='赞踩状态'),
        ),
    ]
