# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-05 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20180805_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleclassify',
            old_name='pbc',
            new_name='pb',
        ),
        migrations.RenameField(
            model_name='articletag',
            old_name='pbt',
            new_name='pb',
        ),
        migrations.RenameField(
            model_name='personalblog',
            old_name='pb',
            new_name='u',
        ),
    ]
