# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-06 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_auto_20180805_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleclassify',
            old_name='pbc',
            new_name='blog',
        ),
        migrations.RenameField(
            model_name='articletag',
            old_name='pbt',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='blogarticledetail',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='repository.BlogArticle', verbose_name='所属文章'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称'),
        ),
    ]
