# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20180806_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back', to='repository.ArticleComment', verbose_name='回复评论'),
        ),
        migrations.AlterField(
            model_name='articlestatus',
            name='status',
            field=models.BooleanField(choices=[(0, '赞'), (1, '踩')], verbose_name='赞踩状态'),
        ),
    ]
