# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-10 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20180808_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlestatus',
            name='status',
            field=models.BooleanField(choices=[(1, '踩'), (0, '赞')], verbose_name='赞踩状态'),
        ),
        migrations.AlterField(
            model_name='blogarticledetail',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.BlogArticle', verbose_name='所属文章'),
        ),
    ]
