# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-11 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20180810_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('detail', models.TextField()),
                ('status', models.IntegerField(choices=[(2, '处理中'), (3, '已处理'), (1, '未处理')], default=1)),
                ('create_time', models.CharField(max_length=32)),
                ('solution', models.TextField(blank=True, null=True)),
                ('solve_time', models.DateTimeField(blank=True, null=True)),
                ('evaluate', models.IntegerField(blank=True, choices=[(1, '不是很舒服'), (2, '可还行'), (4, 'nice'), (3, '舒服舒服')], default=2, null=True)),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='h', to='repository.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u', to='repository.User')),
            ],
            options={
                'verbose_name_plural': '报障表',
                'db_table': 'Trouble',
            },
        ),
        migrations.AlterField(
            model_name='articlestatus',
            name='status',
            field=models.BooleanField(choices=[(0, '赞'), (1, '踩')], verbose_name='赞踩状态'),
        ),
    ]
