# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-11 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20180811_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='create_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='evaluate',
            field=models.IntegerField(blank=True, choices=[(3, '舒服舒服'), (1, '不是很舒服'), (2, '可还行'), (4, 'nice')], default=2, null=True),
        ),
    ]
