# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-11 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20180811_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='evaluate',
            field=models.IntegerField(blank=True, choices=[(4, 'nice'), (2, '可还行'), (3, '舒服舒服'), (1, '不是很舒服')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='status',
            field=models.IntegerField(choices=[(1, '未处理'), (3, '已处理'), (2, '处理中')], default=1),
        ),
    ]
