# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-11 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20180811_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trouble',
            name='create_time',
        ),
        migrations.AlterField(
            model_name='trouble',
            name='evaluate',
            field=models.IntegerField(blank=True, choices=[(1, '不是很舒服'), (2, '可还行'), (3, '舒服舒服'), (4, 'nice')], default=2, null=True),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='status',
            field=models.IntegerField(choices=[(1, '未处理'), (2, '处理中'), (3, '已处理')], default=1),
        ),
    ]
