# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-11 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_auto_20180811_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='trouble',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articlestatus',
            name='status',
            field=models.BooleanField(choices=[(0, '赞'), (1, '踩')], verbose_name='赞踩状态'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='evaluate',
            field=models.IntegerField(blank=True, choices=[(3, '舒服舒服'), (2, '可还行'), (4, 'nice'), (1, '不是很舒服')], default=2, null=True),
        ),
    ]
